// Generated by BDD-to-Cypress — 2026-05-01
describe('Buscar Playwright no Google', () => {
  it('should execute scenario', () => {
    cy.visit('https://www.google.com');
    cy.get('textarea#APjFqb').clear().type('Playwright{enter}');
    cy.contains('Playwright').should('be.visible');
  });
});
