// src/generator/cypressGenerator.js
import Handlebars from 'handlebars';

const template = Handlebars.compile(
`// Generated by BDD-to-Cypress — {{date}}
describe('{{{name}}}', () => {
  it('should execute scenario', () => {
    {{#each steps}}
    {{{this}}}
    {{/each}}
  });
});
`
);

export function generateCypress(data) {
  return template({
    ...data,
    date: new Date().toISOString().split('T')[0],
  });
}
